version: '2.3'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: dockerfile
    environment: 
      - STATS_HOST=172.17.0.1
      - STATS_PORT=7000
    scale: 2
    ports:
      - "9010-9011:9000"

  user-proxy:
    # build:
    #   context: ./loadbalancer
    #   dockerfile: dockerfile
    image: nginx-loadbalancer
    ports:
      - "9500:80"
    volumes:
      - ./user_proxy.nginx.log:/var/log/nginx
    links:
      - user-service
    environment: 
      - IP_1=172.17.0.1
      - PORT_1=9010
      - IP_2=172.17.0.1
      - PORT_2=9011

  stats-service:
    build:
      context: ./stats-service
      dockerfile: dockerfile
    ports:
      - "7000:9000"

  api-service:
    build:
      context: ./api
      dockerfile: dockerfile
    environment: 
      - USERS_HOST=172.17.0.1
      - USERS_PORT=9500
      - STATS_HOST=172.17.0.1
      - STATS_PORT=7000
    scale: 2
    restart: always
    ports:
      - "10000-10001:80"

  api-proxy:
    image: nginx-loadbalancer
    ports:
      - "3000:80"
    volumes:
      - ./api-proxy-logs:/var/log/nginx
    links:
      - api-service
    environment: 
      - IP_1=172.17.0.1
      - PORT_1=10000
      - IP_2=172.17.0.1
      - PORT_2=10001